config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'home' => 'static_pages#home'

  get 'subjects' => 'subjects#index'

  get 'instructor/index'

  get 'course/index'

  post 'courses/enroll'
  get 'admin/index'
  get 'search' => 'courses#index'
  get 'instructors' => 'instructor#index'
  get 'logout' => 'sessions#destroy'
  resources :users
  resources :courses
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_and_belongs_to_many :users

  def self.search(course , subject_id)
    if course != "" && subject_id != ""
      where("name LIKE ? AND cast(subject_id as text) LIKE ?", "%#{course}%","%#{subject_id}%")
    elsif subject_id != "" && course == ""
      where("cast(subject_id as text) LIKE ?", "%#{subject_id}%")
    elsif course != "" && subject_id == ""
      where("name LIKE ?", "%#{course}%")
    else
      puts "enter something"
    end
  end
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  has_and_belongs_to_many :courses


  def enroll(course_id)
    course = Course.find_by(id: course_id.to_i)
    self.courses << course
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :exception


  protected

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: "Please log in"
      end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authorize
  respond_to :js, :html
  def index
    if params[:search]
      search = true
      @courses = Course.search(params[:search],params[:identification]['identification'])
    else
      search = false
      @courses = Course.all
    end


    respond_to do |format|
      format.html #do i need this?
      format.js
    end

  end

  def enroll
    current_user.enroll(params[:course_id])
    @course = Course.find_by(id: params[:course_id] )
  end

  def show
    @course = Course.find_by(id: params[:id])
  end

end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController
  before_filter :authorize
  def index
    @instructors = Instructor.order(:last)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      log_in user
      redirect_to home_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to courses_url, notice: "Logged out"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :authorize
  def index
    @subjects = Subject.order(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def enroll

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to home_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password_digest, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    return @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/courses/_course.html.erb
<div class="container-fluid">
  <tr>
    <td><%= link_to course.name, course %></td>

    <td>
      <%= form_tag(controller: "courses", action: "enroll", method: "put", class: "nifty_form") do %>
        <%= hidden_field_tag :course_id, course.id %>
        <%= submit_tag "Enroll" %>
      <%end%>
    </td>
  </tr>

</div>

app/views/courses/_search.html.erb
<!DOCTYPE html>

  <script type='text/javascript'>
    document.onkeypress = function(event) {
      $('form#search-form').trigger('submit.rails');
    }
    document.onclick = function(event){
      $('form#search-form').trigger('submit.rails');
    }
  </script>

  <div class="container">
    <%= form_tag(courses_path, :method => "get", id: "search-form",remote: true, :html => {:class =>"search-form"}) do %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Course Search</h2>
      </div>
      <div class="panel-body">
        <div class="row">
        	<div class="col-md-6">
            <div class="form-horizontal">
              <div class="input-group">
                <div class="ddl-select input-group-btn">
                  <%= collection_select(:identification,:identification, Subject.all, :identification, :name, :prompt => true,:html =>{:class=>'subject-select'})%>
                </div>
              </div>
            </div>
            <div>
              <%= text_field_tag :search, params[:search], placeholder: "Search Courses", class: "text-field" %>
            </div>
          </div>
        </div>
        <div class="panel-body">
        	<div class="row">
            <h1>Search Results...</h1>
            <table class ="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody id='courses'>
                <% if @courses != nil %>
                  <%= render :partial => @courses %>
              </tbody>
                <% else %>
                  <p> No Results </p>
                <%end%>
            </table>
            <div id="results" class="well"></div>
          </div>
        </div>
      </div>
    </div>
      <% end %>
  </div>

app/views/courses/index.html.erb
<%= render 'search' %>

<div id="results">
</div>

app/views/courses/index.js.erb
$('#courses').html("<%= j(render @courses) %>");

app/views/courses/search.html.erb
<%= render 'search' %>

app/views/courses/show.html.erb
<div class="panel panel-default">
    <h1> <%= @course.name %> </h1>
    <div class="panel-body"><%= @course.description %></div>
    <div class="panel-body"><%= @course.code %></div>
</div>

app/views/instructor/index.html.erb
<h1> Instructors </h1>
<table class ="table table-hover">
  <thead>
    <tr>
      <th>Name</th>

      <th>Email</th>

    </tr>
  </thead>


  <tbody>
    <% @instructors.each do |inst| %>
      <tr>
        <div class="container-fluid">
          <td><%= inst.last%>, <%= inst.first %></td>
          <td><%= inst.email %>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Course Catalog</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><h1><medium><%= link_to 'Course Catalog', home_url%><large></h1></a>
      </div>
      <ul class="nav navbar-nav">
      </ul>
      <p class="navbar-text navbar-right">
        <% if current_user %>
          <div class="btn-group pull-right">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Signed in as <%= current_user.name %> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><a><%= link_to "Log out", logout_path , class: 'btn-default'%></a></li>
              <li><a><%= link_to "Profile", current_user , class: 'btn-default'%></a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </div>
        <% end %>
      </p>
      <p class="navbar-text pull-right"></p>
    </div>
  </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1 class="centered text-center">Home</h1>
<div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-body">
      <p class="centered text-center"> <%= link_to "Courses", courses_url %></p></div>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <p class="centered text-center"> <%= link_to "Subjects", subjects_url %></p></div>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <p class="centered text-center"> <%= link_to "Instructors", instructors_url %></p>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <p class="centered text-center"> <%= link_to "Search Courses", search_url %></p>
    </div>
  </div>
</div>


<% if current_user != nil %>
<h1 class="centered text-center">Enrolled Classes</h1>
  <div class="panel-group">
  <% current_user.courses.each do | course | %>
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="centered text-center"> <%= course.name %> </p>
      </div>
    </div>
  <%end%>
</div>
<%end%>

app/views/subject/index.html.erb
<h1>Subjects</h1>

<table class ="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>


  <tbody>
    <% @instructors.each do |inst| %>
      <tr>
        <div class="container-fluid">
          <td><%= inst.name %>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subjects/index.html.erb
<h1>Subjects</h1>

<table class ="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>


  <tbody>
    <% @subjects.each do |inst| %>
      <tr>
        <div class="container-fluid">
          <td><%= inst.name %>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset>

  <div class="field">
    <%= f.label :name, 'Username' %><br>
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br>
    <%= f.password_field :password, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, 'Confirm' %>
    <p><%= f.password_field :password_confirmation, size: 40 %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>
<% if notice %>
  <p id="notice"><%= notice %></p>
➤ <% end %>
<table class ="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <div class="container-fluid">
          <td><%= user.name %></td>
          <td><btn-default><%= link_to 'Show', user %></btn></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-success' %></li>
<% #end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', home_url %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>